AppBundle\Entity\Product:
  type: entity
  table: product
  id:
    id:
      type: integer
      generator: { strategy: AUTO }
  fields:
    name:
      type: string
      length: 50
    description:
      type: text
    price:
      type: decimal
      scale: 2
    vat:
      type: integer
    categoryId:
      type: integer